name: Generate PDF index

on:
  push:
    paths:
      - 'pdfs/**.pdf'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.html for each folder (sorted by date in filename)
        run: |
          latest_key="00000000"
          latest_href=""
          latest_label=""

          for dir in pdfs/*/; do
            year=$(basename "$dir")
            out="$dir/index.html"

            {
              echo "<!DOCTYPE html>"
              echo "<html lang='ar' dir='rtl'>"
              echo "<head>"
              echo "<meta charset='UTF-8' />"
              echo "<meta name='viewport' content='width=device-width, initial-scale=1' />"
              echo "<title>الواجبات البيتية $year - مَدْرَسَةُ الرَّافِدَينِ العَرَبِيَّة</title>"
              echo "<link rel='stylesheet' href='../../style.css' />"
              echo "<link rel='icon' type='image/png' sizes='96x96' href='../../logo/favicon-96x96.png'>"
              echo "</head>"
              echo "<body>"

              # HEADER
              echo "<header>"
              echo "  <div class='logo' onclick=\"window.location.href='../../index.html'\">"
              echo "    مَدْرَسَةُ الرَّافِدَينِ العَرَبِيَّة"
              echo "    <img src='../../logo/ArraRundLogo.png' alt='Logo' class='school-logo' />"
              echo "  </div>"
              echo "  <nav>"
              echo "    <div class='hamburger' onclick='toggleMenu()'>☰</div>"
              echo "    <ul id='menu'>"
              echo "      <li><a href='../../index.html'>الصفحة الرئيسية</a></li>"
              echo "      <li><a href='../../hausaufgaben.html'>الواجبات البيتية</a></li>"
              echo "      <li><a href='../../about.html'>عن المدرسة</a></li>"
              echo "      <li><a href='../../bilder.html'>معرض الصور</a></li>"
              echo "      <li><a href='../../ads.html'>إعلانات</a></li>"
              echo "      <li><a href='../../kontakt.html'>اتصل بنا</a></li>"
              echo "    </ul>"
              echo "  </nav>"
              echo "</header>"

              echo "<main>"
              echo "  <h1>الواجبات البيتية للعام الدراسي $year</h1>"
              echo "  <ul id='pdf-list'>"
            } > "$out"

            # PDFs sammeln (ohne Subshell-Probleme)
            tmp="$(mktemp)"
            while IFS= read -r -d '' pdf; do
              file=$(basename "$pdf")
              if [[ "$file" =~ ([0-9]{2})([0-9]{2})([0-9]{4}) ]]; then
                dd="${BASH_REMATCH[1]}"
                mm="${BASH_REMATCH[2]}"
                yyyy="${BASH_REMATCH[3]}"
                key="$yyyy$mm$dd"
                label="الواجب البيتي ليوم — $dd.$mm.$yyyy"
              else
                key="00000000"
                label="$file"
              fi
              href="${file// /%20}"

              # Neueste Datei merken
              if [[ "$key" > "$latest_key" ]]; then
                latest_key="$key"
                latest_href="$dir$href"
                latest_label="$label"
              fi

              printf '%s\t%s\t%s\n' "$key" "$href" "$label" >> "$tmp"
            done < <(find "$dir" -maxdepth 1 -type f -name '*.pdf' -print0)

            if [[ -s "$tmp" ]]; then
              sort -rz -k1,1 "$tmp" | while IFS=$'\t' read -r key href label; do
                echo "    <li><a href=\"$href\" target=\"_blank\">$label</a></li>" >> "$out"
              done
            else
              echo "    <p>لا توجد ملفات بعد.</p>" >> "$out"
            fi
            rm -f "$tmp"

            {
              echo "  </ul>"
              echo "  <p><a href='../../hausaufgaben.html'>العودة</a></p>"
              echo "</main>"

              # FOOTER
              echo "<footer>"
              echo "  <div class='social-icons'>"
              echo "    <a href='https://www.facebook.com/profile.php?id=100063760595206#' target='_blank'><img src='../../logo/facebook-svgrepo-com.svg' alt='Facebook' width='24' height='24'></a>"
              echo "    <a href='https://www.instagram.com/arrafidain_kulturverein_e.v._/' target='_blank'><img src='../../logo/instagram-svgrepo-com.svg' alt='Instagram' width='24' height='24'></a>"
              echo "    <a href='https://t.me/arrafidainschule' target='_blank'><img src='../../logo/telegram-svgrepo-com.svg' alt='Telegram' width='24' height='24'></a>"
              echo "  </div>"
              echo "</footer>"
              echo "<script src='../../script.js'></script>"
              echo "</body></html>"
            } >> "$out"

          done

          # JSON-Datei für neueste Hausaufgabe schreiben
          mkdir -p pdfs
          if [[ -n "$latest_href" ]]; then
            echo "{ \"href\": \"$latest_href\", \"label\": \"$latest_label\" }" > pdfs/latest_homework.json
          else
            echo "{ \"href\": \"\", \"label\": \"لا توجد ملفات بعد\" }" > pdfs/latest_homework.json
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdfs/*/index.html pdfs/latest_homework.json
          git commit -m "Auto-generate PDF indexes and latest homework JSON" || echo "No changes"
          git push
